### ISSUE TITLE
Use at least 2 APIs

### ISSUE THREAD

**Issue by EbonyMeadows** [flyboy85749/Project-1#2]
find 2 APIs
-youTube
-Pinterest

**Comment by John-Hoy** [comment]
we edited our idea to be instead of pulling pics/videos to making a nutrition finding website so the new api's we are using is https://developer.nutritionix.com/docs/v1_1 and we will use a second one for finding the location(in the works)

**Comment by John-Hoy** [comment]
we settled on our second api to be google maps

**Comment by flyboy85749** [comment]
we have at least two apis in use
